### PR TITLE
app: remove tic-tac-toe

### PR DESCRIPTION
**Pull request by leograba**
This app is broken on Torizon OS 6. It is not being actively maintained as a 3rd-party app, so removing it.

### CODE REVIEW

**Comment by tkfu** [comment]
Needs a rebase, I think, but other than that LGTM.

**Review by charles2910 — APPROVED** [review]
Right! Two questions, did you try to bump weston to 3 and see if works (I'm just curious - probably would need 4:1 cgroup rules) and are you sure that removing here is all it takes to remove from the feed?

**Comment by leograba** [comment]
> Right! Two questions, did you try to bump weston to 3 and see if works (I'm just curious - probably would need 4:1 cgroup rules) and are you sure that removing here is all it takes to remove from the feed?

I didn't try to use a newer weston.

It will be removed from the feed, although not immediately. The feed is updated on its own frequency.

**Comment by leograba** [comment]
> Needs a rebase, I think, but other than that LGTM.

Rebased

**Review by tkfu — APPROVED** [review]

**Comment by leograba** [comment]
> If you want to ping me when you merge this, I can manually run the pipeline right away so the feed gets updated.

I think it's ok to wait, there is no urgency that it can't wait another day.

**Pull request merged**
